name: fedi3
description: Personal ActivityPub instance client (Flutter UI + Rust core)
publish_to: "none"
version: 0.9.6+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  desktop_drop: ^0.5.0
  ffi: ^2.1.2
  file_selector: ^1.1.0
  flutter_widget_from_html_core: ^0.15.0
  http: ^1.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.2
  desktop_webview_window: ^0.2.3
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_android_video: ^1.3.8
  media_kit_libs_ios_video: ^1.1.4
  mime: ^1.0.6
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  encrypt: ^5.0.3
  pointycastle: ^3.9.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.0
  inno_build: ^0.4.0
  package_info_plus: ^8.0.2
  crypto: ^3.0.3
  archive: ^3.6.1
  audioplayers: ^6.1.0
  local_notifier: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/notify.mp3
    - assets/sounds/chat.mp3

dependency_overrides:
  flutter_secure_storage_linux: ^3.0.0








